### ISSUE TITLE
Changed parts in diff are blinking.

### ISSUE THREAD

**Issue by prosoitos** [jesseduffield/lazygit#1274]
**Describe the bug**

Starting a couple of commits ago, I started to get very distracting blinking of any of the change sections in the diff. I thought that everybody would complain about it and that it would get resolved, but to my surprise, no issue got open on this. I am using [st](https://st.suckless.org/) and maybe it doesn't do it with another terminal emulator???

New release doesn't fix it which is why I finally decided to mention it.

**Desktop (please complete the following information):**

 - OS: Arch Linux 5.11.13-arch1-1
 - Lazygit Version: 0.27.4.r28.e42387d0-1

Thanks!!

**Comment by jesseduffield** [comment]
@prosoitos are you able to test out latest master? I fixed a minor rendering issue on that that might have caused your problem.

Also, does st run on mac? I'm not sure how to get it, the download page is a little hard to decipher
![image](https://user-images.githubusercontent.com/8456633/114688023-a6239f00-9d57-11eb-8983-4464934174ae.png)

**Comment by prosoitos** [comment]
Thank you for looking into this! 🙂 

The problem persists after pulling your latest commit.

st on MacOS: no idea!

On Linux, to install it, you can clone the repo (`git clone https://git.suckless.org/st`), `cd` into it and run `make clean install`.

**Comment by ristillu** [comment]
This is happening for me too @prosoitos. I thought it was a new feature 😄 and I quite like it. I has definitely appeared for me since v0.27.x. I am not using st, I am using xfce4-terminal and I highly doubt anything has changed on its end. I am also using diff-so-fancy.

**Comment by jesseduffield** [comment]
@prosoitos what is the value of your TERM env var? If it's `st-256color`, this is the file that would be used for configuring tcell on startup: https://github.com/jesseduffield/lazygit/blob/master/vendor/github.com/gdamore/tcell/v2/terminfo/s/simpleterm/term.go. Looking there, the blink escape sequence is the same as in the xterm-256color one, so I assume there is some other reason why the blinking is happening.

as for xfce @ristillu there isn't actually a blink escape sequence defined. I'm not sure if it's given a default somewhere, but worth mentioning.

**Comment by prosoitos** [comment]
Yes, my `$TERM` is `st-256color`.

@ristillu, maybe it has to do with diff-so-fancy then ...

**Comment by ristillu** [comment]
My `$TERM` is `xterm-256color`. My diff-so-fancy is 1.4.0. My git is 2.31.1. Anyway, it's not an issue for me but I'm happy to help debug/provide a point of reference. I'm absolutely sure it changed with v0.27.x though.

**Comment by prosoitos** [comment]
It is a big issue for me. I find it so distracting that I have temporarily stopped using lazygit. So I would certainly be happy to get to the bottom of this.

In any event, thanks @ristillu and @jesseduffield for trying to help 🙂

**Comment by ristillu** [comment]
@prosoitos I just turned off diff-so-fancy and the blinking stops. I switched back and forth between enabled/disabled diff-so-fancy and it's clearly the cause for me.

**Comment by jesseduffield** [comment]
Interesting, I wonder what in diff-so-fancy's output might cause that. At any rate while we look for a fix you might want to try out delta: https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md#delta

**Comment by ristillu** [comment]
@jesseduffield for fun I just checked out v0.26.1 and go installed and the blinking is not present with diff-so-fancy. Then I checked out v0.27 and the blinking is present. So something in the changeset from v0.26.1 to v0.27 has changed how diff-so-fancy handles the paging. I did a quick search of diff-so-fancy issues but they're not particularly active and there's no mention of "blink" or "flash".

**Comment by jesseduffield** [comment]
@ristillu we switched from termbox to tcell in v0.27 so that would have done it

**Comment by prosoitos** [comment]
Thanks so much @ristillu for all the troubleshooting.

@jesseduffield I did try delta, but liked diff-so-fancy a lot more.

Any hope of an upcoming fix? Now that the problem has been diagnosed, what are your thoughts? Thanks!!!

**Comment by prosoitos** [comment]
For now, I decided to downgrade to v0.26.1.

It's not a long term solution, but I hope there will be a fix at some point and in the meantime, this was the best option for me.

**Comment by jesseduffield** [comment]
@prosoitos the master branch has an updated tcell version which recently fixed an issue in another ticket. Could you give that a try?

**Comment by ristillu** [comment]
@jesseduffield it's still blinking for me with commit 9fdf92b2.

**Comment by prosoitos** [comment]
diff-so-fancy got updated yesterday on Arch Linux and the changed parts are now very different (they are displayed in reversed color).

This fixed the problem for me, so I can now use the latest version of lazygit again (and, as an added great news, the package made it to the Arch Linux Community package repository!!! 😄 ).

**Comment by prosoitos** [comment]
So, whatever was a problem probably still remains and could still be an issue with some future version of diff-so-fancy or other pager. But since the problem is resolved for me for now, I am ok to close this issue.

But I will wait to hear from @ristillu before doing so in case the diff-so-fancy update did not solve the issue on his end.

**Comment by ristillu** [comment]
Weird. I updated diff-so-fancy (by updating my cloned repo) to their latest version v1.4.2 and it's still blinking for me.
