### ISSUE TITLE
Lazygit can't open files with spaces in the name

### ISSUE THREAD

**Issue by SentientCoffee** [jesseduffield/lazygit#1403]
**Describe the bug**
Whenever I try to open a file using `o` in the main window, or when I try to use a command on it in the custom command window using `:`, I keep getting errors that the system cannot find the file, with the given file name being an incomplete version of the actual file name (up to the first space in the name). In some rare cases, I can't perform normal lazygit commands such as `Shift+D > discard unstaged changes` because it can't find the file due to the spaces problem (will give a fatal git error that the specified file was not in the index).

**To Reproduce**
1. Open any repo in lazygit
2. Make any file in any directory, one or both should have spaces in the name
3. See changes in lazygit window
4. Try to open file using `o` or perform a git command on it using `:` (for example, `git add <file-name>`)
4. See error: `The system cannot find the file <incomplete-file-name>`

**Expected behavior**
Lazygit should open the file normally regardless of whether or not there are spaces in the name.

**Screenshots**
Highlighting the file I want to open:
![image](https://user-images.githubusercontent.com/22991229/127223742-90a337ce-8719-49be-8826-b79b5551f850.png)

After pressing `o`:
![image](https://user-images.githubusercontent.com/22991229/127223778-2e3d7398-00eb-4b63-b1b0-dc46a97a6e53.png)
![image](https://user-images.githubusercontent.com/22991229/127223798-d3792047-4baa-4670-904e-113366739c63.png)

Trying to open via custom command:
![image](https://user-images.githubusercontent.com/22991229/127224041-e4173d28-27ff-457c-809c-8b6001639462.png)
![image](https://user-images.githubusercontent.com/22991229/127224062-f7a4a92c-93ad-441f-ac33-e3eb8a7363e0.png)
![image](https://user-images.githubusercontent.com/22991229/127224079-25b61a29-704b-47d7-bfd6-fb225407edba.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Lazygit version v0.28.2

**Additional context**
It seems like the part where it opens via a lazygit command could just be fixed by adding quotes to the command as it runs, looking at the command log it seems like it is being passed as is to the command line and it gets broken because of the space delimeters on the command line:
![image](https://user-images.githubusercontent.com/22991229/127224714-39871c06-1dff-4ae9-832e-6b25ba9faa88.png)
(Should be `C:\Windows\System32\cmd.exe /c start  "Assets/Prefabs/Player Data/Player (Remove the other one after dataObj is copied over).prefab"` or something like that)

**Comment by mjarkk** [comment]
Might be related to https://github.com/jesseduffield/lazygit/issues/1350

**Comment by mjarkk** [comment]
Is this fixed in the last release?

**Comment by SentientCoffee** [comment]
Hi, sorry, I've been off of Github for a while and I had not seen this.

I just unpackaged the latest release (0.29) and I still have the same issue.

**Comment by mjarkk** [comment]
Hmm that's annoying can you give us more information so we can maybe re-produce your issue.

**Comment by SentientCoffee** [comment]
What information would you like? It's still the same issue as in the first comment, files names with spaces don't open when pressing `o`.

Here are a few examples with different files:
![image](https://user-images.githubusercontent.com/22991229/134573097-45d2fb01-f47a-4460-9eb5-d44ebeb21461.png)
![image](https://user-images.githubusercontent.com/22991229/134573282-7cf32cea-7265-438d-a622-1347d72290ac.png)
![image](https://user-images.githubusercontent.com/22991229/134573396-8181c847-5789-4675-85fb-2bf035dea06b.png)

All of these give the same error: `The system cannot find the file <incomplete-file-name>`
