### ISSUE TITLE
commits with more than one word in the messsage fail

### ISSUE THREAD

**Issue by amrelk** [jesseduffield/lazygit#141]
**Describe the bug**
If I type more than one word as the commit message, it fails:
```
error: pathspec 'word2' did not match any file(s) known to git.
error: pathspec 'word3' did not match any file(s) known to git.
```
I realize this is probably a problem on my end but I have no idea how to resolve it.

**To Reproduce**
1. open lazygit
2. stage a file
3. commit
4. type a message >1 word long

**Expected behavior**
To commit.

**Screenshots**
![message](https://user-images.githubusercontent.com/13759043/44063895-2fabe0ce-9f28-11e8-94a6-b298a5e247fe.png)
![error](https://user-images.githubusercontent.com/13759043/44063896-2fbfe09c-9f28-11e8-9593-f51c62c090df.png)

**Desktop**
 - OS: Windows
 - Lazygit Version v0.1.55
 - git version 2.18.0.windows.1

**Additional context**
Tested with both cmd and Powershell

**Comment by jesseduffield** [comment]
@amrelk how did you install this version? Is this a binary from the releases page, or did you install it some other way?

**Comment by amrelk** [comment]
it occurs when I installed it from one of the binaries, or with go get

**Comment by jesseduffield** [comment]
I've put up a PR https://github.com/jesseduffield/lazygit/pull/142 that should fix this. Could you pull that down and test it on your machine?

**Comment by amrelk** [comment]
it looks like it's still having the same problem. just to be sure, I should checkout feature/quoted-messages and run `go run main.go`, right?

**Comment by jesseduffield** [comment]
Yes that's correct. It looks like the refactor that's just been pushed is the culprit. I'll need to have another look at this after work. In the meantime I believe using shift+c can provide an alternative - as this opens the commit message in an editor (defaulting to vim)

**Comment by jesseduffield** [comment]
@amrelk I've pushed some more fixes. Could you try again now?

**Comment by amrelk** [comment]
works great in 0.1.59. thanks!
