### ISSUE TITLE
Panic when tag is checked out.

### ISSUE THREAD

**Issue by codazoda** [jesseduffield/lazygit#153]
**Describe the bug**
When I run `lazygit`, while I have a tag checked out, I get a Panic.

**To Reproduce**
1. Create a tag on your project on an oldish commit
2. Checkout that tag with something like `git checkout tag/v1.0.0`
3. Start `lazygit`

**Expected behavior**
Expected lazygit to open and maybe to show me what commit I was on somehow.

**Screenshots**

<img width="1562" alt="screen shot 2018-08-15 at 10 01 17 am" src="https://user-images.githubusercontent.com/527246/44158666-800f4380-a072-11e8-9f8f-a33c7ce3bb4b.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 10.13.6
 - Version: commit=652237d48fabc401d795e9703c12fd37e2ec478e, build date=2018-08-14T09:23:19Z, version=0.1.59

**Comment by jesseduffield** [comment]
I just confirmed that this does crash on 0.1.59, but not on the latest version, so if you update your issue should be resolved :)

**Comment by glvr182** [comment]
@codazoda Is your issue fixed now?

**Comment by glvr182** [comment]
Still getting the error @jesseduffield 
I found that the panic comes from 
```
func (c *GitCommand) CurrentBranchName() (string, error) {
	output, err := c.OSCommand.RunCommandWithOutput("git symbolic-ref --short HEAD")
	if err != nil {
		return "", err
	}
	return utils.TrimTrailingNewline(output), nil
}
```

**Comment by dawidd6** [comment]
Maybe we can add `--quiet` to `git symbolic-ref --short HEAD` and then check if output returned by this command is empty. If it is, then we can get tag by `git tag --points-at HEAD` and display this as current branch.

**Comment by glvr182** [comment]
@jesseduffield  @codazoda should work in the version since @jesseduffield finished detached heads see #328

**Comment by jesseduffield** [comment]
this should be resolved now
