### ISSUE TITLE
`delta` crashes with the latest version `0.31`

### ISSUE THREAD

**Issue by tiwood** [jesseduffield/lazygit#1564]
**Describe the bug**
With the latest release `delta` crashes directly after the start of lazygit. The right panel stays frozen and if lazygit closes you can see a `cannot kill child process` error message.

**To Reproduce**
Use delta as pager:
```yaml
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
```

**Expected behavior**
Paging should work and not crash 🧨️

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 12
 - Lazygit Version 0.31
 - delta 0.9.2

**Additional context**

**Comment by Cokile** [comment]
I have the same issue:
``` yaml
git:
  paging:
    colorarg: always
    pager: delta --paging=never --diff-highlight
```

OS: macOS 11.4
Lazygit Version 0.31
delta 0.9.2

**Comment by briandipalma** [comment]
Removing the paging=never seems to fix the crash but the diff is still messed up, it's quite squished.

**Comment by jesseduffield** [comment]
Taking a look into this now

**Comment by jesseduffield** [comment]
fixed in https://github.com/jesseduffield/lazygit/pull/1568

**Comment by jesseduffield** [comment]
fixed in v0.31.1 :)

**Comment by Cokile** [comment]
![image](https://user-images.githubusercontent.com/8230448/140631688-aa6c7ee2-23c6-44b2-811b-b2bf73e46634.png)

@jesseduffield Thanks for the nice work. But is 0.31.1 tagged to wrong commit?

**Comment by jesseduffield** [comment]
ahh yes, that was definitely intentional. What I meant to say is that it's fixed in v0.31.2!

**Comment by jesseduffield** [comment]
hmm homebrew core rejected the PR as a potential duplicate. Sounds like I'll need to re-release another version later

**Comment by MikaelElkiaer** [comment]
I am still seeing lots of errors when switching to delta:
```
panic: runtime error: index out of range [3] with length 3
```

With lazygit config:
```
git:
  pull:
    mode: 'auto'
  overrideGpg: true
  paging:
    colorArg: always
    pager: delta --dark --paging=never
```

And git config:
```
[core]
    pager = delta --dark
[interactive]
    diffFilter = delta --dark --color-only
```
