### ISSUE TITLE
MacOS config.yml PATH in ~/.config

### ISSUE THREAD

**Issue by oscarmlage** [jesseduffield/lazygit#1669]
**The `~/.config/lazygit/config.yml` is not taken into account in MacOS**

Tried to add some config stuff to `~/.config/lazygit/config.yml` in MacOS but it didn't work out. It worked when the config was added to `~/Library/Application Support/lazygit/config.yml` as it says in the [docs](https://github.com/dawidd6/lazygit-debian/blob/master/docs/Config.md).

**Proposal**

Would it be posible to add `~/.config/lazygit/config.yml` as a valid path for the config in MacOS too?, taking in account some kind of priority if both are present.

**Additional context**

I mean, as some other software reads the config from there probably it's more friendly to have the config in `~/.config` too, thinking about dealing with dotfiles, put them in a repo, maintaining etc...

**Comment by RyannDaGreat** [comment]
I second this...I tried both 
```
/Users/Ryan/Library/Application Support/Ryan/lazygit/config.yml
/Users/Ryan/Library/Application Support/lazygit/config.yml
/Users/Ryan/.config/lazygit/config.yml
```
but none of them work on my Catalina mac :\

**Comment by Ryooooooga** [comment]
```sh
export XDG_CONFIG_HOME="$HOME/.config"
```

works for me.

**Comment by blakedietz** [comment]
This does not work for me for `fish`.
macOS: 13.4

```fish
fish --version
fish, version 3.6.1
set -U XDG_CONFIG_HOME "$HOME/.config"
lazygit -cd
/Users/blakedietz/Library/Application Support/lazygit
```

**Comment by ChrisMcD1** [comment]
/close

This should now be fixed in latest. https://github.com/jesseduffield/lazygit/commit/59f06501736dc49f3e35f7858acafa5cda13b845

**Comment by LorenzoBettini** [comment]
Unless I miss something, this is still an issue in macOS, with

```
lazygit --version
commit=, build date=, build source=homebrew, version=0.48.0, os=darwin, arch=arm64, git version=2.49.0
```

Even if I wipe `~/Library/Application Support/lazygit` and put the config.yml in `~/.config/lazygit/config.yml`, Lazygit ignores my configuration and recreates a default one in the former directory...

**Comment by stefanhaller** [comment]
It seems that #3989 fell through the cracks and was never merged. I'll see if I can bring it up to date and merge it soon.

In the meantime, `export XDG_CONFIG_HOME="$HOME/.config"` should work, does it not for you @LorenzoBettini?

(Also, you are not using the latest version, please upgrade your homebrew.)

**Comment by LorenzoBettini** [comment]
@stefanhaller yes, setting xdg works.

I commented here because I seemed to understand that was not needed anymore. In fact, you confirm that the fix was not merged.

**Comment by ChrisMcD1** [comment]
My apologies on closing this! Human error on my part. I don't have permissions to re-open, or otherwise I would 😅

**Comment by dhoppe** [comment]
@stefanhaller In my case it does not work. 

```
❯ lazygit --version
commit=, build date=, build source=Homebrew, version=0.55.0, os=darwin, arch=arm64, git version=2.51.0
```

The environment variable `$XDG_CONFIG_HOME` is working as expected. 

```
❯ echo $XDG_CONFIG_HOME
/Users/dhoppe/.config
```

However, Lazygit still searches for a configuration file in the old directory. 

```
❯ lazygit --print-config-dir
/Users/dhoppe/Library/Application Support/lazygit
```

**Edit**: It is working, when I use $LG_CONFIG_FILE instead of $XDG_CONFIG_HOME, but Lazygit still points to the old config directory. 

```
❯ echo $LG_CONFIG_FILE
/Users/dhoppe/.config/lazygit/config.yml
```

```
❯ lazygit --print-config-dir
/Users/dhoppe/Library/Application Support/lazygit
```

<img width="1392" height="1180" alt="Image" src="https://github.com/user-attachments/assets/811ce098-fb2a-4f84-9047-a3533ea56595" />

**Comment by stefanhaller** [comment]
@dhoppe I don't know what to say; works for me.

```
❯ XDG_CONFIG_HOME=/foo/bar lazygit --print-config-dir
/foo/bar/lazygit
```

**Comment by spacetime-labs** [comment]
Having `export XDG_CONFIG_HOME="$HOME/.config"` in my `.zshrc` did it for me. But I hope .config is the default directory later on.
