### ISSUE TITLE
Main window not refreshed when dropping stash

### ISSUE THREAD

**Issue by wolfgangwalther** [jesseduffield/lazygit#1737]
**Describe the bug**
With multiple stashes present, dropping a stash does not refresh the main window. It should show the newly selected stash's contents - but it keeps showing the old stash, that was already dropped.

**Desktop:**
 - OS: Linux
 - version: `commit=v0.32.2, build date=2022-01-17T09:11:06Z, build source=binaryRelease, version=0.32.2, os=linux, arch=amd64`

**Comment by jesseduffield** [comment]
This should be fixed on master. Would you be able to build from master and check @wolfgangwalther ?

**Comment by wolfgangwalther** [comment]
Hm. Built with latest master, but still the same:

`commit=bed185eb, build date=20220128.085127, build source=unknown, version=v0.32.1.bed185eb, os=linux, arch=amd64`

**Comment by jesseduffield** [comment]
Whoops. Fixed in https://github.com/jesseduffield/lazygit/pull/1739

**Comment by wolfgangwalther** [comment]
Yes, that works!
