### ISSUE TITLE
Unexpected error when opening lazygit in the home directory

### ISSUE THREAD

**Issue by nullishamy** [jesseduffield/lazygit#2066]
**Describe the bug**
When opening lazygit in the home directory (which has no git repo), lazygit throws an error instead of using the regular "no repo" dialog.

**To Reproduce**
1. Cd to `~`
2. Launch lazygit
3. Observe

**Expected behavior**
The "Not in a git repository. Create a new git repository? (y/n): " prompt should appear

**Desktop:**
 - OS: Arch
 - Lazygit Version 0.35

**Additional context**
The error:
```
2022/07/29 22:03:10 An error occurred! Please create an issue at: https://github.com/jesseduffield/lazygit/issues

*errors.errorString repository does not exist
github.com/jesseduffield/lazygit/pkg/app/app.go:52 (0x556da154f736)
github.com/jesseduffield/lazygit/main.go:154 (0x556da155d190)
runtime/proc.go:250 (0x556da0f4a7d3)
runtime/asm_amd64.s:1571 (0x556da0f78261)
```

**Comment by mark2185** [comment]
Could you please post your `~/.config/lazygit/state.yml`?

Does it occur in other directories that are not `git` repositories?

**Comment by nullishamy** [comment]
In other non-git dirs, it just runs the regular prompt. ```yml
lastupdatecheck: 0
recentrepos:
- /tmp/git-test
- /tmp/lazygit
- /home/amy/.config/nvim
- /home/amy/Projects/projects-bot
startuppopupversion: 5
customcommandshistory:
- q
hidecommandlog: false
```

**Comment by mark2185** [comment]
Your `$HOME` wouldn't happen to be a _bare_ `git` repo, would it? That's not currently supported. 
I'm not sure what minimal set of folders/files is necessary for a bare `git` repo, but the usual suspects are `HEAD`, `config`, `description` and a handful of directories.

Would you be willing to build `lazygit` manually in order to get a more informative stacktrace?

**Comment by nullishamy** [comment]
Ah yeah, it had a repo from some stuff I did ages ago, works now. Would it be possible to add more info to the error? Seems like that would benefit people.

**Comment by mark2185** [comment]
It sure could, all one needs to invoke is `git rev-parse --is-bare-repository` to see if we need to try and load the current directory.

Would you like to contribute, maybe? This seems like a trivial task, compared to the `git rebase` thingy.

**Comment by nullishamy** [comment]
Sure, I can open a PR.

**Comment by nullishamy** [comment]
Done.

**Comment by mark2185** [comment]
Thanks!

Just for future reference - it's better to leave it to `github` to close up the issue when the PR merges because technically this issue wasn't solved yet since it didn't hit `master`. I doubt anyone will stumble upon this issue in the meantime, but still.
