### ISSUE TITLE
Unable to access submodule config file error

### ISSUE THREAD

**Issue by hdbalyozsht** [jesseduffield/lazygit#2148]
When I enter a submodule I get the following error 14 times at the top of right area for one submodule which I could not enter

![Screenshot from 2022-09-02 14-20-03](https://user-images.githubusercontent.com/13886544/188128796-4a64d825-ba5e-418c-95fd-f8edc036a049.png)
![Screenshot from 2022-09-02 14-20-30](https://user-images.githubusercontent.com/13886544/188128814-42fd73d9-9acc-441e-981d-2c3589c5e960.png)

**Comment by mark2185** [comment]
Please fill out the `bug report template`.

Are you able to enter the submodule through the `cli`, do you have sufficient permissions?

**Comment by mark2185** [comment]
Please note the _note_ at the bottom of the report:
```
**Note:** please try updating to the latest version or [manually building](https://github.com/jesseduffield/lazygit/#manual) the latest `master` to see if the issue still occurs.
```

Your version (`0.27.4`) is `1 year and 5 months` old. It's likely the bug was solved in the meantime.

**Comment by hdbalyozsht** [comment]
`commit=367b0d331836c90c015bf0c45f88612f3d94d08a, build date=2022-07-20T09:27:56Z, build source=binaryRelease, version=0.35, os=linux, arch=amd64`

Still getting the error

**Comment by mark2185** [comment]
Alright, can you run `git status` in the submodule without problems?

Do the permissions match to the parent repo? (`ls -l` will list the permissions)

Does it work if you clone the repository once again, somewhere else? Just a `git clone --recursive <link> some-other-name` should suffice.

**Comment by hdbalyozsht** [comment]
- There is no problem at git status
- Permissions are the same as other submodules
- I get the same error in my another project repository that includes submodules

**Comment by mark2185** [comment]
Do you by any chance use an old `ssh` key? [Something similar on SO](https://stackoverflow.com/questions/25957125/git-submodule-permission-denied)

**Comment by hdbalyozsht** [comment]
`git submodule update --init --recursive` works well for me. I can also push and fetch without any problem. Any ssh issue would couse such problems. I also check specified config file owner and read permissions. It seems ok

`-rw-rw-r--   1 prihex prihex  765 Eyl  6 14:18 config`

**Comment by hdbalyozsht** [comment]
I tried cloning a public widespread github repo. Same result

```
git clone https://github.com/ArduPilot/ardupilot.git
cd ardupilot/
git submodule update --init --recursive
lazygit
```

- Then go to submodules.
- Select `modules/uavcan` which is the first
- Go to local branches `main`

![image](https://user-images.githubusercontent.com/13886544/188956718-18768956-bb1d-4df4-b869-ae632d9b7c9d.png)

**Comment by mark2185** [comment]
Are the submodules also cloned over `https`? 

Check the `.gitmodules` file in the root of the repo, it should start with this:
```
[submodule "modules/uavcan"]
	path = modules/uavcan
	url = https://github.com/DroneCAN/libuavcan.git
```

**Comment by hdbalyozsht** [comment]
Yes. All protocols are https.

```bash
prihex@pc:~/projects/test/ardupilot$ cat .gitmodules 
[submodule "modules/uavcan"]
	path = modules/uavcan
	url = https://github.com/DroneCAN/libuavcan.git
[submodule "modules/waf"]
	path = modules/waf
	url = https://github.com/ArduPilot/waf.git
[submodule "modules/gbenchmark"]
	path = modules/gbenchmark
	url = https://github.com/google/benchmark.git
[submodule "modules/mavlink"]
	path = modules/mavlink
	url = https://github.com/ArduPilot/mavlink
[submodule "gtest"]
	path = modules/gtest
	url = https://github.com/ArduPilot/googletest
[submodule "modules/ChibiOS"]
	path = modules/ChibiOS
	url = https://github.com/ArduPilot/ChibiOS.git
[submodule "modules/gsoap"]
	path = modules/gsoap
	url = https://github.com/ArduPilot/gsoap
[submodule "modules/DroneCAN/DSDL"]
	path = modules/DroneCAN/DSDL
	url = https://github.com/DroneCAN/DSDL.git
[submodule "modules/CrashDebug"]
	path = modules/CrashDebug
	url = https://github.com/ardupilot/CrashDebug
[submodule "modules/DroneCAN/pydronecan"]
	path = modules/DroneCAN/pydronecan
	url = https://github.com/DroneCAN/pydronecan
[submodule "modules/DroneCAN/dronecan_dsdlc"]
	path = modules/DroneCAN/dronecan_dsdlc
	url = https://github.com/DroneCAN/dronecan_dsdlc
[submodule "modules/DroneCAN/libcanard"]
	path = modules/DroneCAN/libcanard
	url = https://github.com/DroneCAN/libcanard
```

**Comment by hdbalyozsht** [comment]
Any progress?

**Comment by mark2185** [comment]
Sadly no, since it's unfortunately not reproducible. At least I can't reproduce it.

Unless you're willing to debug, I'm afraid we can't do much at this point :confused:
