### ISSUE TITLE
Move state.yml to $XDG_STATE_HOME/lazygit/state.yml

### ISSUE THREAD

**Issue by adriel-tech** [jesseduffield/lazygit#2794]
**Is your feature request related to a problem? Please describe.**

When using a dotfile manager like stow I end up moving state.yml between my many machines
and state.yml seems like something that should be specific to each machine.

**Describe the solution you'd like**

Move state.yml to $XDG_STATE_HOME/lazygit/state.yml
Which defaults too '~/.local/state/lazygit/state.yml' other programs such as neovim do this as an example.

**Describe alternatives you've considered**

The ability to disable state.yml or the ability to set its location in config.yml.

**Comment by zhongdai** [comment]
I got the same problem, the state file should not live together with the config file.

**Comment by stefanhaller** [comment]
@adriel-tech @zhongdai This should be fixed by #2936, could you test that please?

**Comment by wiraki** [comment]
Hello, I am confused. I see #2936 has been merged, but I still have the `state.yml` in my $XDG_CONFIG_HOME.

**Comment by stefanhaller** [comment]
The new code looks for the file in a few places, including where it used to be. When it finds it in any of them, it writes it back to the same location. This was a deliberate decision, [here's](https://github.com/jesseduffield/lazygit/pull/2936#issuecomment-1866740773) some discussion about it.

If you want it in the new place, you'll have to move it there manually (or delete it from the old place if you don't care about what's stored in it, it will be recreated in the new place then).

**Comment by wiraki** [comment]
Thanks, that's cleared it! I peeked at that discussion but missed that part.

**Comment by stefanhaller** [comment]
Fixed by #2936.
