### ISSUE TITLE
Panic due to 0 indexing

### ISSUE THREAD

**Issue by Sigmanificient** [jesseduffield/lazygit#4858]
### Describe the bug

```
panic: runtime error: index out of range [0] with length 0

goroutine 72 [running]:
github.com/stefanhaller/git-todo-parser/todo.parseLine({0xc00015a960, 0x50}, 0x23)
	github.com/stefanhaller/git-todo-parser@v0.0.7-0.20250429125209-dcf39e4641f5/todo/parse.go:113 +0xd4f
github.com/stefanhaller/git-todo-parser/todo.Parse({0x10ff8c0?, 0xc00090c3f0?}, 0x23)
	github.com/stefanhaller/git-todo-parser@v0.0.7-0.20250429125209-dcf39e4641f5/todo/parse.go:33 +0x150
github.com/jesseduffield/lazygit/pkg/commands/git_commands.(*CommitLoader).getRebasingCommits(0xc0001fa000, 0xc00024a0f0, 0x1)
	github.com/jesseduffield/lazygit/pkg/commands/git_commands/commit_loader.go:350 +0x16b
github.com/jesseduffield/lazygit/pkg/commands/git_commands.(*CommitLoader).getHydratedRebasingCommits(0xc0001fa000, 0xc00024a0f0, 0x18?)
	github.com/jesseduffield/lazygit/pkg/commands/git_commands/commit_loader.go:255 +0x1d
github.com/jesseduffield/lazygit/pkg/commands/git_commands.(*CommitLoader).MergeRebasingCommits(0xc0001fa000, 0xc00024a0f0, {0x1910860, 0x0, 0x0})
	github.com/jesseduffield/lazygit/pkg/commands/git_commands/commit_loader.go:177 +0x24c
github.com/jesseduffield/lazygit/pkg/commands/git_commands.(*CommitLoader).GetCommits(0xc0001fa000, {0x1, {0x0, 0x0}, {0x0, 0x0}, 0x1, {0xf2552f, 0x4}, {0x11087c0, ...}, ...})
	github.com/jesseduffield/lazygit/pkg/commands/git_commands/commit_loader.go:79 +0x75
github.com/jesseduffield/lazygit/pkg/gui/controllers/helpers.(*RefreshHelper).refreshCommitsWithLimit(0xc0001a8f80)
	github.com/jesseduffield/lazygit/pkg/gui/controllers/helpers/refresh_helper.go:322 +0x378
github.com/jesseduffield/lazygit/pkg/gui/controllers/helpers.(*RefreshHelper).refreshCommitsAndCommitFiles(0xc0001a8f80)
	github.com/jesseduffield/lazygit/pkg/gui/controllers/helpers/refresh_helper.go:273 +0x1c
github.com/jesseduffield/lazygit/pkg/gui/controllers/helpers.(*RefreshHelper).Refresh.func2.1.1({0x0?, 0x0?})
	github.com/jesseduffield/lazygit/pkg/gui/controllers/helpers/refresh_helper.go:106 +0x13
github.com/jesseduffield/gocui.(*Gui).onWorkerAux(0xc0002d6000, 0x0?, {0x1107180?, 0xc00039a6c0?})
	github.com/jesseduffield/gocui@v0.3.1-0.20250711082438-4aa4fd0b4d22/gui.go:721 +0x65
github.com/jesseduffield/gocui.(*Gui).OnWorker.func1()
	github.com/jesseduffield/gocui@v0.3.1-0.20250711082438-4aa4fd0b4d22/gui.go:708 +0x2b
created by github.com/jesseduffield/gocui.(*Gui).OnWorker in goroutine 1
	github.com/jesseduffield/gocui@v0.3.1-0.20250711082438-4aa4fd0b4d22/gui.go:707 +0x90
```

### Version info:

lazygit: 0.54.2
git: 2.49.0

### Additional context

This occurred during a rebase:
```
git status
interactive rebase in progress; onto 5052d3e0ebe8
Last commands done (189 commands done):
   reset 4a0a6e1204f5 
   pick 1737cb9fe9fd tinymist: 0.13.22 -> 0.13.24
  (see more in file /home/sigmanificient/repos/nixpkgs/.git/worktrees/nixpkgs3/rebase-merge/done)
Next commands to do (3530 remaining commands):
   label tinymist-0-13-22-0-13-24-437148-
   reset 24d2d0fd641e 
  (use "git rebase --edit-todo" to view and edit)
You are currently editing a commit during a rebase.
  (use "git commit --amend" to amend the current commit)
  (use "git rebase --continue" once you are satisfied with your changes)

nothing to commit, working tree clean
```

**Comment by stefanhaller** [comment]
Thanks for the report. It's a very obvious bug and the fix is very simple, but I'm curious how you ran into this bug. Did you edit your rebase-todo file manually? Or are you using some other git client that might have touched it? I'm asking because git usually doesn't create the data that caused the crash (which, concretely, is a `merge` line without a trailing comment).

See https://github.com/stefanhaller/git-todo-parser/pull/2 for the fix.

**Comment by Sigmanificient** [comment]
I was using `nixpkgs-review` like usual, it's a tool that automatically create worktree to review prs in nixpkgs. After editing one of the commits within lazygit, i created that situation where i couldn't opened it again!

There is probably something i did that caused a mess, but i figured that it could be helpful to report that index bound issue, since it seems trivial to fix

**Comment by stefanhaller** [comment]
> After editing one of the commits within lazygit

What exactly does that mean? Did you press `e` on it, or `r`? Either way, it sounds like you should be able to replicate the problem then? Because I can't, and I just want to understand it better before merging the fix.

**Comment by prosoitos** [comment]
I am getting the same:

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/gui.(*OptionsMapMgr).renderContextOptionsMap.func4(...)
        github.com/jesseduffield/lazygit/pkg/gui/options_map.go:63
github.com/samber/lo.Map[...](...)
        github.com/samber/lo@v1.53.0/slice.go:49
github.com/jesseduffield/lazygit/pkg/gui.(*OptionsMapMgr).renderContextOptionsMap(0x36e457489308)
        github.com/jesseduffield/lazygit/pkg/gui/options_map.go:56 +0x1617
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).renderContextOptionsMap(0x36e45710a7e0?)
        github.com/jesseduffield/lazygit/pkg/gui/options_map.go:29 +0x4b
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).layout(0x36e456ef4908, 0x36e456de0f00)
        github.com/jesseduffield/lazygit/pkg/gui/layout.go:192 +0x7c9
github.com/jesseduffield/lazygit/pkg/gocui.ManagerFunc.Layout(0x36e457104230?, 0x36e456e43408?)
        github.com/jesseduffield/lazygit/pkg/gocui/gui.go:691 +0x19
github.com/jesseduffield/lazygit/pkg/gocui.(*Gui).flush(0x36e456de0f00)
        github.com/jesseduffield/lazygit/pkg/gocui/gui.go:1157 +0xbf
github.com/jesseduffield/lazygit/pkg/gocui.(*Gui).processEvent(0x36e456de0f00)
        github.com/jesseduffield/lazygit/pkg/gocui/gui.go:785 +0x39b
github.com/jesseduffield/lazygit/pkg/gocui.(*Gui).MainLoop(0x36e456de0f00)
        github.com/jesseduffield/lazygit/pkg/gocui/gui.go:741 +0xea
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0x36e456ef4908, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}})
        github.com/jesseduffield/lazygit/pkg/gui/gui.go:946 +0x5fd
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunAndHandleError.func1()
        github.com/jesseduffield/lazygit/pkg/gui/gui.go:957 +0x48
github.com/jesseduffield/lazygit/pkg/utils.SafeWithError(0x563c967aed45?)
        github.com/jesseduffield/lazygit/pkg/utils/utils.go:80 +0x56
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunAndHandleError(0x36e456ef4908, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}})
        github.com/jesseduffield/lazygit/pkg/gui/gui.go:956 +0xf6
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(...)
        github.com/jesseduffield/lazygit/pkg/app/app.go:277
github.com/jesseduffield/lazygit/pkg/app.Run({0x563c978e9418?, 0x36e456e90420?}, 0x36e45704ec00, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, ...}})
        github.com/jesseduffield/lazygit/pkg/app/app.go:48 +0xda
github.com/jesseduffield/lazygit/pkg/app.Start(0x36e456eb1ef8, {0x0, 0x0})
        github.com/jesseduffield/lazygit/pkg/app/entry_point.go:177 +0xe1a
main.main()
        github.com/jesseduffield/lazygit/main.go:23 +0x93
```

after the last update while using it the way I normally do.

lazygit: 0.62.0
OS: 7.0.10-arch1-1

**Comment by prosoitos** [comment]
Downgrading solves the issue so something broke (at least for me) with v. 0.62.

I can open a new issue if need be as this one was about an old bug that has been addressed. Also now (at least for me), the situation appears without doing anything special. Update to 0.62 and launch `lazgit` and that's it.

**Comment by stefanhaller** [comment]
@prosoitos This is actually not the same at all, it's a very different crash, just has a similar panic message.

Fixed by #5655, thanks for reporting.

You must have `<disabled>` keybindings in your config file, why is that? I'm really just curious how people work.

**Comment by prosoitos** [comment]
Ah! Thanks for the quick reply! 🙂 

I disabled all the kbd for the commands that I don't use to reduce the risk of using them accidentally.

For instance, I disabled all the `xxx-alt` and `xxx-alt2` (I don't need 2 or 3 kbd for one command. This is a good idea to make the tool work for more people out of the box, but at the level of the individual user, it doesn't add anything and increases the risk of doing something unintentional).

I also disabled the commands that I never use (e.g. I never submit PRs from lazygit, so all that is off), again, to prevent accidents.

And I disabled one command that I use extremely rarely and that I did trigger by accident in the past: `stashAllChanges`. I could have made a kbd harder to accidentally trigger for that one, but I decided to just disable the kbd (I can still go get the command in the popup if I ever need it). I got caught several times by unintentionally stashing things due to the easy kbd, not notice it, and then have to go through the hassle of merging that stash when I noticed it days later.

In short, it's really all about preventing to do things without meaning to.

I also changed the kbd for dramatic actions to kbd harder to press than the default ones for that same reason (e.g. I changed all the `d` to `<c-d>` for the various discard commands. A single key press felt way too risky to me for those).

Call me clumsy with my keyboard I guess 😆

**Comment by prosoitos** [comment]
I guess I'll have to set a kbd for stashing everything with the new change. I'll just make it very hard to press 😉 

Never mind: I can still get there via `viewStashOptions`.

**Comment by stefanhaller** [comment]
@prosoitos I just released 0.62.1 which fixes the crash.

**Comment by Sigmanificient** [comment]
i kept receiving notification in my old issue, so at least i was made aware quickly about the update 🙃

**Comment by prosoitos** [comment]
Thanks for the quick fix and release!

And sorry for necrobumping an old issue that had nothing to do with it 😬
