### ISSUE TITLE
lazygit crashes on launch

### ISSUE THREAD

**Issue by tagesmutter** [jesseduffield/lazygit#756]
**Describe the bug**
lazygit just crashes when it's launched in one of my repos. Other repos seem to work.

It seems to be an array index bug, maybe due to files with umlauts in their filename?
It worked on previous versions, I think up until 0.14.x or so.

Here is the message:
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/jesseduffield/lazygit/pkg/commands.(*BranchListBuilder).obtainBranches(0xc000393998, 0x15, 0xc000393860, 0x55b0150ccb7e)
        /home/sed/.cache/yay/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/commands/branch_list_builder.go:54 +0x60c
github.com/jesseduffield/lazygit/pkg/commands.(*BranchListBuilder).Build(0xc000393998, 0xc000393aa0, 0xc0000c94a0, 0xc0003dff00)
        /home/sed/.cache/yay/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/commands/branch_list_builder.go:95 +0x45
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).refreshBranches.func1(0xc00013e000, 0xc0003939e4, 0x3)
        /home/sed/.cache/yay/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/gui/branches_panel.go:70 +0x54
github.com/jesseduffield/gocui.(*Gui).consumeevents(0xc00013e000, 0xc000393b28, 0x2)
        /home/sed/.cache/yay/lazygit-git/src/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:483 +0x1ea
github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc00013e000, 0xc000000003, 0xc000393ca0)
        /home/sed/.cache/yay/lazygit-git/src/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:465 +0x217
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).Run(0xc000138000, 0x0, 0x0)
        /home/sed/.cache/yay/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:1033 +0x608
github.com/jesseduffield/lazygit/pkg/gui.(*Gui).RunWithSubprocesses(0xc000138000, 0x0, 0x0)
        /home/sed/.cache/yay/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/gui/gui.go:1042 +0x42
github.com/jesseduffield/lazygit/pkg/app.(*App).Run(0xc00025ad90, 0xc00018ea00, 0xc00025ad90)
        /home/sed/.cache/yay/lazygit-git/src/src/github.com/jesseduffield/lazygit/pkg/app/app.go:158 +0x6d
main.main()
        /home/sed/.cache/yay/lazygit-git/src/src/github.com/jesseduffield/lazygit/main.go:67 +0x75c

**Expected behavior**
lazygit doesn't crash ;-)

**Desktop (please complete the following information):**
 commit=2d8ed5e2, build date=20200327.081646, build source=unknown, version=v0.18.2d8ed5e2, os=linux, arch=amd64

**Additional context**
It worked on previous versions, I think up until 0.14.x or so.

**Comment by jesseduffield** [comment]
could you try the latest version? I think the issue is resolved there

**Comment by tagesmutter** [comment]
Sorry to report that it's still not working with version:
commit=d1395b15, build date=20200327.093220, build source=unknown, version=v0.18.d1395b15, os=linux, arch=amd64

**Comment by jesseduffield** [comment]
Could you please paste the stacktrace of the error on the new version?

**Comment by band-a-prend** [comment]
I tested the 0.19 with simple test repo and lazygit crash launching after I amended commit with addition gpg sign to it.

For other repos the same error. Sorry can't copy any text from konsole after crash, so attach screenshot

![lazygit_crash](https://user-images.githubusercontent.com/18756734/78566936-97dba280-7828-11ea-83a7-08a5d98afec7.png)

The `git log` output for changes in `README.md` file:

```
commit bc5b9c10c228ff137527378900730edb14ffc578 (HEAD -> master)
gpg: Signature made Mon Apr  6 16:56:05 2020 MSK
gpg:                using RSA key <MY_FINGERPRINT_VALUE>
gpg: Good signature from "user (gpg-key for github account) <user@mail.test>" [ultimate]
Author: user <user@mail.test>
Date:   Mon Apr 6 16:37:50 2020 +0300

    update readme file
    
    New updates to
    This file

commit b2381e5f5a83aa3e3d6872caeffff732ca0d218c
Author: user <user@mail.test>
Date:   Mon Apr 6 16:36:12 2020 +0300

    init readme file
```

**Comment by glvr182** [comment]
I cant seem to reproduce this error.
I:
 * Created a test repo
 * Setup signing key
 * Created a dummy file
 * Commited with signature
 * Created changed a few things
 * Ammended staged things to commit

Is this what you did?

**Comment by band-a-prend** [comment]
Does you .gitconfig contains option `showSignature = true` (global or local) if I change it to false then it seems works

**Comment by glvr182** [comment]
Added that to my config and then I got the error.
Gonna test a few things, will let you know what I find

**Comment by glvr182** [comment]
#779 should fix this, can you try it?

**Comment by band-a-prend** [comment]
I could check it later but I'm not sure that it's the same as initial bug.

**Comment by glvr182** [comment]
Good call, changed the pr details a bit sothat it doesnt close this issue

**Comment by band-a-prend** [comment]
@glvr182 
I checked patch and looks it now OK. And the signature is displayed in commit message window too.

**Comment by micmarty** [comment]
similar issue:
![image](https://user-images.githubusercontent.com/12485656/87038077-828e5f80-c1ed-11ea-91b9-5e2059fc0c77.png)

**Comment by jesseduffield** [comment]
Looks like the original bug here is fixed. @micmarty your bug appears to be a dupe of https://github.com/jesseduffield/lazygit/issues/905

I've just now merged https://github.com/jesseduffield/lazygit/pull/980 which will display a proper error rather than panic when the git version is less than 2.0

Closing :)
