### ISSUE TITLE
got painc error : index out of range

### ISSUE THREAD

**Issue by Xib1uvXi** [jesseduffield/lazygit#95]
OS ENV :  Ubuntu 18.04 

Git version : 2.17.1

run command : lazygit

git status: 
```
On branch master
nothing to commit, working tree clean
```

```text
panic: runtime error: index out of range

goroutine 1 [running]:
main.branchInfoFromLine(0xc42026a000, 0x2c, 0xc4200cd680, 0x25, 0x26, 0x0, 0xc42013d988, 0x747bf9)
        /home/qydev/go/src/github.com/jesseduffield/lazygit/gitcommands.go:557 +0x100
main.getBranches(0x842496, 0xa, 0xc420256600)
        /home/qydev/go/src/github.com/jesseduffield/lazygit/gitcommands.go:584 +0x15f
main.getGitBranches(0xc420198120, 0x841032, 0x8)
        /home/qydev/go/src/github.com/jesseduffield/lazygit/gitcommands.go:618 +0x159
main.refreshBranches.func1(0xc420198120, 0x1, 0xc42013dbf0)
        /home/qydev/go/src/github.com/jesseduffield/lazygit/branches_panel.go:111 +0x97
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).consumeevents(0xc420198120, 0x0, 0x0)
        /home/qydev/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:414 +0x17c
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc420198120, 0x0, 0x0)
        /home/qydev/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:396 +0x1f5
main.run(0x0, 0x0)
        /home/qydev/go/src/github.com/jesseduffield/lazygit/gui.go:261 +0x161
main.main()
        /home/qydev/go/src/github.com/jesseduffield/lazygit/main.go:121 +0xd7

```

**Comment by jesseduffield** [comment]
The function branchInfoFromLine() processes the output from the command
```
git reflog -n100 --pretty='%cr|%gs' --grep-reflog='checkout: moving' HEAD
```
It expects each line to look like '3 days ago|checkout: moving from feature/use-dep to master'
it them strips it down to 3 days ago master using this regex `"\\|.*\\s"`(replacing everything that matches with a string).

If there's nothing confidential in the output of that git reflog command, please post it here. Otherwise, could you check to see if there are any lines in the output that don't match our expected format?

**Comment by songjian925** [comment]
![image](https://user-images.githubusercontent.com/16771263/44071098-c59bdbac-9fb9-11e8-88fa-cc3a452b15f9.png)
only a line

**Comment by jesseduffield** [comment]
This should be resolved in https://github.com/jesseduffield/lazygit/pull/146
But it looks like the cause of the issue is due to different locales defining time units differently. The original code expected something like '7 days ago' and then processed that to get '7d'.  So although this will solve the bug, it might look funny in the list.

There is currently a PR up https://github.com/jesseduffield/lazygit/pull/137 for doing i18n, feel free to contribute to that effort if you want to get involved in any translations :)

Please pull down the latest release and see if this solves your issue

**Comment by glvr182** [comment]
@Xib1uvXi Is your bug fixed in the latest version?

**Comment by Xib1uvXi** [comment]
no, still the same bug

go get -v github.com/jesseduffield/lazygit
cd project src
run  lazygit 

```
panic: runtime error: index out of range

goroutine 1 [running]:
main.branchInfoFromLine(0xc42029a000, 0x2c, 0xc42029e000, 0x25, 0x26, 0x0, 0xc420137988, 0x747bf9)
	/home/qydev/go/src/github.com/jesseduffield/lazygit/gitcommands.go:557 +0x100
main.getBranches(0x842496, 0xa, 0xc42027c1c0)
	/home/qydev/go/src/github.com/jesseduffield/lazygit/gitcommands.go:584 +0x15f
main.getGitBranches(0xc420122240, 0x841032, 0x8)
	/home/qydev/go/src/github.com/jesseduffield/lazygit/gitcommands.go:618 +0x159
main.refreshBranches.func1(0xc420122240, 0x1, 0xc420137bf0)
	/home/qydev/go/src/github.com/jesseduffield/lazygit/branches_panel.go:111 +0x97
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).consumeevents(0xc420122240, 0xc420137d88, 0x0)
	/home/qydev/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:414 +0x17c
github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui.(*Gui).MainLoop(0xc420122240, 0x0, 0x0)
	/home/qydev/go/src/github.com/jesseduffield/lazygit/vendor/github.com/jesseduffield/gocui/gui.go:396 +0x1f5
main.run(0x0, 0x0)
	/home/qydev/go/src/github.com/jesseduffield/lazygit/gui.go:261 +0x161
main.main()
	/home/qydev/go/src/github.com/jesseduffield/lazygit/main.go:121 +0xd7

```

run ```git reflog -n100 --pretty='%cr|%gs' --grep-reflog='checkout: moving' HEAD```
```
3 周前|checkout: moving from dev to master
3 周前|checkout: moving from master to dev
3 周前|checkout: moving from 1.11 to master
3 周前|checkout: moving from master to 1.11
3 周前|checkout: moving from 1.11 to master
3 周前|checkout: moving from master to 1.11
3 周前|checkout: moving from mvp to master
5 周前|checkout: moving from master to mvp
4 周前|checkout: moving from vgo_dev to master
4 周前|checkout: moving from master to vgo_dev
4 周前|checkout: moving from mvp to master
5 周前|checkout: moving from master to mvp
4 周前|checkout: moving from mvp to master
5 周前|checkout: moving from master to mvp
4 周前|checkout: moving from vgo_dev to master
4 周前|checkout: moving from master to vgo_dev
5 周前|checkout: moving from mvp to master
5 周前|checkout: moving from master to mvp
7 周前|checkout: moving from dev to master
7 周前|checkout: moving from master to dev
7 周前|checkout: moving from dev to master
7 周前|checkout: moving from master to dev
8 周前|checkout: moving from dev to master
7 周前|checkout: moving from master to dev
8 周前|checkout: moving from dev to master
8 周前|checkout: moving from master to dev
2 个月前|checkout: moving from dev to master
2 个月前|checkout: moving from master to dev
3 个月前|checkout: moving from dev to master
3 个月前|checkout: moving from dev to dev
3 个月前|checkout: moving from master to dev
3 个月前|checkout: moving from dev to master
3 个月前|checkout: moving from master to dev
3 个月前|checkout: moving from dev to master
3 个月前|checkout: moving from master to dev
3 个月前|checkout: moving from dev to master
3 个月前|checkout: moving from master to dev
```

**Comment by Xib1uvXi** [comment]
@glvr182 yep
